FROM python:3.11-slim


# Copia o script de instalação
COPY setup_instant_client.sh .

# Modifica permissões do arquivo concedendo permissão de execução para usuario atual
# Executando scrip bash
RUN chmod +x setup_instant_client.sh && ./setup_instant_client.sh

# Define variáveis de ambiente
ENV LD_LIBRARY_PATH=/.oracle/instantclient_19_23/
ENV PYTHONUNBUFFERED=1


WORKDIR "/app"
COPY requirements_oracle.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc \
        libaio1 \
        libpq-dev \
        libssl-dev \
        python3-dev \
        musl-dev \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv dlt_venv \
    && ./dlt_venv/bin/pip install --no-cache-dir -r requirements_oracle.txt

ENV PATH="/app/dlt_venv/bin:$PATH"

# Mantém o container rodando
CMD ["tail", "-f", "/dev/null"]
